
SoundAlerterSpells = {

    auraApplied = {

        [20580] = "shadowmeld",
        [20554] = "berserking",
        [20594] = "stoneform",
        [20572] = "bloodfury",
        [7744] = "willoftheforsaken",
		[1259799] = "eluneslight",
		[20577] = "cannibalize",
		[1259686] = "skysight",

        [408024] = "survivalinstincts",
        [29166] = "innervate",
        [22812] = "barkskin",
        [17116] = "naturesswiftness",
        [17329] = "naturesgrasp",
        [22842] = "frenziedregeneration",
        [20687] = "starfall",
        [417141] = "berserk",
        [1850] = "dash",
        [9821] = "dash",

        [1022] = "handofprotection",
        [5599] = "handofprotection",
        [10278] = "handofprotection",
        [1044] = "handoffreedom",
        [642] = "divineshield",
        [1020] = "divineshield",
        [6940] = "handofsacrifice",
        [407804] = "divinesacrifice",
        [498] = "divineprotection",
        [5573] = "divineprotection",

        [2983] = "sprint",
        [8696] = "sprint",
        [11305] = "sprint",
        [462873] = "cloakofshadows",
        [13750] = "adrenalinerush",
        [5277] = "evasion",
        [14177] = "coldblood",
        [1856] = "vanish",
        [1857] = "vanish",

        [402913] = "enragedregeneration",
        [1719] = "recklessness",
        [871] = "shieldwall",
        [12975] = "laststand",
        [18499] = "berserkerrage",
        [20230] = "retaliation",
        [23920] = "spellreflection",
        [12292] = "sweepingstrikes",
        [9632] = "bladestorm",
        [12328] = "deathwish",

        [402004] = "painsuppression",
        [10060] = "powerinfusion",
        [6346] = "fearward",
        [425294] = "dispersion",
        [14751] = "innerfocus",

        [433255] = "shamanisticrage",
        [379] = "earthshield",
        [408514] = "earthshield",
        [408519] = "earthshield",
        [408510] = "watershield",

        [11958] = "iceblock",
        [12042] = "arcanepower",
        [12472] = "coldsnap",
        [12043] = "presenceofmind",
        [28682] = "combustion",


        [1223758] = "thebeastwithin",
        [19263] = "deterrence",

        [17941] = "shadowtrance",
		[403789] = "metamorphosis",
        [416863] = "auramastery",
        [429125] = "icyveins",
        [401724] = "hotstreak",
        [429303] = "deepfreeze",
    },
    auraRemoved = {

        [9632] = "bladestormdown",
        [1719] = "recklessnessdown",
        [871] = "shieldwalldown",
        [12328] = "deathwishdown",

        [498] = "divineprotectiondown",
        [10278] = "protectiondown",
        [642] = "bubbledown",

        [462873] = "cloakdown",
		[13750] = "adrenalinerushdown",
        [5277] = "evasiondown",

        [402004] = "psdown",
        [425294] = "dispersiondown",

        [11958] = "iceblockdown",


        [20687] = "starfalldown",

        [19263] = "deterrencedown",
        [1223758] = "beastwithindown",
    },
    castStart = {

        [635] = "bigheal",
        [639] = "bigheal",
        [647] = "bigheal",
        [1026] = "bigheal",
        [1042] = "bigheal",
        [3472] = "bigheal",
        [10328] = "bigheal",
        [10329] = "bigheal",
        [25292] = "bigheal",
        [2054] = "bigheal",
        [2055] = "bigheal",
        [6063] = "bigheal",
        [6064] = "bigheal",
        [2060] = "bigheal",
        [332] = "bigheal",
        [547] = "bigheal",
        [913] = "bigheal",
        [939] = "bigheal",
        [959] = "bigheal",
        [8005] = "bigheal",
        [10395] = "bigheal",
        [10396] = "bigheal",
        [25357] = "bigheal",
        [5185] = "bigheal",
        [5186] = "bigheal",
        [5187] = "bigheal",
        [5188] = "bigheal",
        [5189] = "bigheal",
        [6778] = "bigheal",
        [8903] = "bigheal",
        [9758] = "bigheal",
        [9888] = "bigheal",
        [9889] = "bigheal",
        [25297] = "bigheal",
        [2006] = "resurrection",
        [2010] = "resurrection",
        [10880] = "resurrection",
        [10881] = "resurrection",
        [20770] = "resurrection",
        [7328] = "resurrection",
        [10322] = "resurrection",
        [10324] = "resurrection",
        [20772] = "resurrection",
        [20773] = "resurrection",
        [2008] = "resurrection",
        [20609] = "resurrection",

        [18658] = "hibernate",
        [2637] = "hibernate",
		[740] = "tranquility",
        [21668] = "starfire",

        [10326] = "turnevil",

        [8129] = "manaburn",
        [9484] = "shackleundead",
        [9485] = "shackleundead",
        [10955] = "shackleundead",
        [605] = "mindcontrol",
        [10911] = "mindcontrol",
        [10912] = "mindcontrol",

        [450600] = "hex",

        [118] = "polymorph",
        [12826] = "polymorph",
        [28272] = "polymorph",
        [28271] = "polymorph",

        [982] = "revivepet",
        [14327] = "scarebeast",

        [6215] = "fear",
        [5484] = "fear2",
        [17928] = "fear2",
        [710] = "banish",
        [18647] = "banish",
        [688] = "summonpet",
        [691] = "summonpet",
        [712] =  "summonpet",
        [697] = "summonpet",
        [20484] = "rebirth",
        [20739] = "rebirth",
        [20742] = "rebirth",
        [20747] = "rebirth",
        [20748] = "rebirth",
        [339] = "roots",
        [1062] = "roots",
        [5195] = "roots",
        [5196] = "roots",
        [9852] = "roots",
        [9853] = "roots",
    },
    castSuccess = {

        [1259718] = "trinket",

        [12051] = "evocation",
        [11958] = "coldsnap",
        [2139] = "counterspell",
        [66] = "invisibility",
		[11366] = "pyroblast",


        [23989] = "readiness",
        [19434] = "aimedshot",
        [14309] = "freezingtrap",
        [13810] = "frosttrap",
        [13809] = "frosttrap",
        [14311] = "freezingtrap",
        [14310] = "freezingtrap",
        [1499] = "freezingtrap",
		[1310687] = "powershot",

        [5138] = "drainmana",
        [17928] = "fear2",
        [19647] = "spelllock",
        [6789] = "deathcoil",
		[17925] = "deathcoil",
        [17926] = "deathcoil",
        [6358] = "seduction",

		[5215] = "prowl",
		[6783] = "prowl",
		[9913] = "prowl",

        [20066] = "repentance",
        [10308] = "hammerofjustice",
        [853] = "hammerofjustice",
        [5588] = "hammerofjustice",
        [5589] = "hammerofjustice",
        [407788] = "avengingwrath",

        [11297] = "sap",
        [6770] = "sap",
        [2070] = "sap",
        [2094] = "blind",
        [1766] = "kick",
        [1767] = "kick",
        [1768] = "kick",
        [1769] = "kick",
        [14185] = "preparation",
        [27617] = "vanish",
        [13877] = "bladeflurry",
        [1784] = "stealth",
        [1785] = "stealth",

        [8143] = "tremortotem",
        [16190] = "manatide",
        [2484] = "earthbind",
        [8177] = "grounding",

        [2457] = "battlestance",
        [71] = "defensestance",
        [2458] = "berserkerstance",
        [676] = "disarm",
        [5246] = "fear3",
        [6552] = "pummel",
        [6554] = "pummel",
        [72] = "shieldbash",

        [10890] = "fear4",
        [34433] = "shadowfiend",
        [422603] = "smokebomb",
        [460651] = "frozenorb",
        [1238787] = "meteor",
        [1245940] = "bloodlust",
        [1833] = "cheapshot",
        [6409] = "cheapshot",
        [14902] = "cheapshot",
        [15487] = "silence",
        [1714] = "curseoftongues",
        [11719] = "curseoftongues",
        [19503] = "scattershot",
        [23601] = "scattershot",
        [440488] = "shockwave",
        [633] = "layonhands",
        [2800] = "layonhands",
        [10310] = "layonhands",
        [17233] = "layonhands",
        [426490] = "rallyingcry",
        [408] = "kidneyshot",
        [8643] = "kidneyshot",
        [27615] = "kidneyshot",
    },
    enemyDebuffs = {
        [2094] = "enemyblinded",
        [11297] = "enemysapped",
        [12826] = "enemypollied",
        [118] = "enemypollied",
        [450600] = "enemyhexxed",
    },
    enemyDebuffdown = {
        [2094] = "blinddown",
        [11297] = "sapdown",
        [118] = "polydown",
        [12826] = "polydown",
        [450600] = "hexdown",
    },
    interruptFriend = {
        [2139] = "friendcountered",
        [1766] = "friendcountered",
    },
    friendCCs = {
        [450600] = "hexfriend",
        [12826] = "polyfriend",
        [118] = "polyfriend",
        [28272] = "polyfriend",
        [28271] = "polyfriend",
        [6215] = "fearfriend",
    },
    friendCCSuccess = {
        [14309] = "friendfrozen",
        [2094] = "blindfriend",
        [5246] = "friendfeared",
        [11297] = "friendsapped",
        [10308] = "friendstunned",
        [2139] = "friendcountered",
        [450600] = "friendhexxed",
        [118] = "friendpoly",
        [12826] = "friendpoly",
        [6215] = "friendfeared",
        [10890] = "friendfeared",
        [17928] = "friendfeared",
    },
    friendCCenemy = {
        [2094] = "enemyblinded",
        [11297] = "enemysapped",
        [450600] = "enemyhexxed",
        [12826] = "enemypollied",
        [118] = "enemypollied",
    },
    enemyDebuffdownAP = {
        [2094] = "blinddown",
        [11297] = "sapdown",
        [450600] = "hexdown",
        [12826] = "polydown",
        [118] = "polydown",
    },
    selfDebuff = {
        [450600] = "hex",
        [12826] = "polymorph",
        [118] = "polymorph",
        [28272] = "polymorph",
        [28271] = "polymorph",
        [12824] = "polymorph",
        [12825] = "polymorph",
        [6215] = "fear",
        [5782] = "fear",
        [6213] = "fear",
        [14309] = "freezingtrap",
        [13810] = "frosttrap",
        [13809] = "frosttrap",
        [14311] = "freezingtrap",
        [1499] = "freezingtrap",
        [5246] = "fear3",
        [17928] = "fear2",
        [2094] = "blind",
        [11297] = "sap",
        [6770] = "sap",
        [10308] = "hammerofjustice",
        [10890] = "fear4",
        [17926] = "deathcoil",
        [5138] = "drainmana",
        [20066] = "repentance",
        [19434] = "aimedshot",
        [24335] = "wyvernsting",
        [6358] = "seduction",
    },
}

SoundAlerterSpellMeta = {

    -- Druid
    barkskin = { "Druid", "Barkskin" },
    berserk = { "Druid", "Berserk" },
    dash = { "Druid", "Dash" },
    roots = { "Druid", "Entangling Roots" },
    frenziedregeneration = { "Druid", "Frenzied Regeneration" },
    hibernate = { "Druid", "Hibernate" },
    innervate = { "Druid", "Innervate" },
    naturesgrasp = { "Druid", "Nature's Grasp" },
    naturesswiftness = { "Druid", "Nature's Swiftness" },
    prowl = { "Druid", "Prowl" },
    rebirth = { "Druid", "Rebirth" },
    starfall = { "Druid", "Starfall" },
    starfalldown = { "Druid", "Starfall" },
    starfire = { "Druid", "Starfire" },
    survivalinstincts = { "Druid", "Survival Instincts" },
    tranquility = { "Druid", "Tranquility" },

    -- Hunter
    aimedshot = { "Hunter", "Aimed Shot" },
    deterrence = { "Hunter", "Deterrence" },
    deterrencedown = { "Hunter", "Deterrence" },
    freezingtrap = { "Hunter", "Freezing Trap" },
    friendfrozen = { "Hunter", "Freezing Trap" },
    frosttrap = { "Hunter", "Frost Trap" },
    readiness = { "Hunter", "Readiness" },
    revivepet = { "Hunter", "Revive Pet" },
    scarebeast = { "Hunter", "Scare Beast" },
    scattershot = { "Hunter", "Scatter Shot" },
    powershot = { "Hunter", "Sniper Shot" },
    beastwithindown = { "Hunter", "The Beast Within" },
    thebeastwithin = { "Hunter", "The Beast Within" },
    wyvernsting = { "Hunter", "Wyvern Sting" },

    -- Mage
    arcanepower = { "Mage", "Arcane Power" },
    coldsnap = { "Mage", "Cold Snap" },
    combustion = { "Mage", "Combustion" },
    counterspell = { "Mage", "Counterspell" },
    deepfreeze = { "Mage", "Deep Freeze" },
    evocation = { "Mage", "Evocation" },
    frozenorb = { "Mage", "Frozen Orb" },
    hotstreak = { "Mage", "Hot Streak" },
    iceblock = { "Mage", "Ice Block" },
    iceblockdown = { "Mage", "Ice Block" },
    icyveins = { "Mage", "Icy Veins" },
    invisibility = { "Mage", "Lesser Invisibility" },
    meteor = { "Mage", "Meteor" },
    enemypollied = { "Mage", "Polymorph" },
    friendpoly = { "Mage", "Polymorph" },
    polydown = { "Mage", "Polymorph" },
    polyfriend = { "Mage", "Polymorph" },
    polymorph = { "Mage", "Polymorph" },
    presenceofmind = { "Mage", "Presence of Mind" },
    pyroblast = { "Mage", "Pyroblast" },

    -- Paladin
    auramastery = { "Paladin", "Aura Mastery" },
    avengingwrath = { "Paladin", "Avenging Wrath" },
    handoffreedom = { "Paladin", "Blessing of Freedom" },
    handofprotection = { "Paladin", "Blessing of Protection" },
    protectiondown = { "Paladin", "Blessing of Protection" },
    handofsacrifice = { "Paladin", "Blessing of Sacrifice" },
    divineprotection = { "Paladin", "Divine Protection" },
    divineprotectiondown = { "Paladin", "Divine Protection" },
    divinesacrifice = { "Paladin", "Divine Sacrifice" },
    bubbledown = { "Paladin", "Divine Shield" },
    divineshield = { "Paladin", "Divine Shield" },
    friendstunned = { "Paladin", "Hammer of Justice" },
    hammerofjustice = { "Paladin", "Hammer of Justice" },
    layonhands = { "Paladin", "Lay on Hands" },
    repentance = { "Paladin", "Repentance" },
    turnevil = { "Paladin", "Turn Undead" },

    -- Priest
    dispersion = { "Priest", "Dispersion" },
    dispersiondown = { "Priest", "Dispersion" },
    fearward = { "Priest", "Fear Ward" },
    innerfocus = { "Priest", "Inner Focus" },
    manaburn = { "Priest", "Mana Burn" },
    mindcontrol = { "Priest", "Mind Control" },
    painsuppression = { "Priest", "Pain Suppression" },
    psdown = { "Priest", "Pain Suppression" },
    powerinfusion = { "Priest", "Power Infusion" },
    fear4 = { "Priest", "Psychic Scream" },
    shackleundead = { "Priest", "Shackle Undead" },
    shadowfiend = { "Priest", "Shadowfiend" },
    silence = { "Priest", "Silence" },

    -- Rogue
    adrenalinerush = { "Rogue", "Adrenaline Rush" },
    adrenalinerushdown = { "Rogue", "Adrenaline Rush" },
    bladeflurry = { "Rogue", "Blade Flurry" },
    blind = { "Rogue", "Blind" },
    blinddown = { "Rogue", "Blind" },
    blindfriend = { "Rogue", "Blind" },
    enemyblinded = { "Rogue", "Blind" },
    cheapshot = { "Rogue", "Cheap Shot" },
    cloakdown = { "Rogue", "Cloak of Shadows" },
    cloakofshadows = { "Rogue", "Cloak of Shadows" },
    coldblood = { "Rogue", "Cold Blood" },
    evasion = { "Rogue", "Evasion" },
    evasiondown = { "Rogue", "Evasion" },
    kick = { "Rogue", "Kick" },
    kidneyshot = { "Rogue", "Kidney Shot" },
    preparation = { "Rogue", "Preparation" },
    enemysapped = { "Rogue", "Sap" },
    friendsapped = { "Rogue", "Sap" },
    sap = { "Rogue", "Sap" },
    sapdown = { "Rogue", "Sap" },
    smokebomb = { "Rogue", "Smoke Bomb" },
    sprint = { "Rogue", "Sprint" },
    stealth = { "Rogue", "Stealth" },
    vanish = { "Rogue", "Vanish" },

    -- Shaman
    bloodlust = { "Shaman", "Bloodlust" },
    earthshield = { "Shaman", "Earth Shield" },
    earthbind = { "Shaman", "Earthbind Totem" },
    grounding = { "Shaman", "Grounding Totem" },
    enemyhexxed = { "Shaman", "Hex" },
    friendhexxed = { "Shaman", "Hex" },
    hex = { "Shaman", "Hex" },
    hexdown = { "Shaman", "Hex" },
    hexfriend = { "Shaman", "Hex" },
    manatide = { "Shaman", "Mana Tide Totem" },
    shamanisticrage = { "Shaman", "Shamanistic Rage" },
    tremortotem = { "Shaman", "Tremor Totem" },
    watershield = { "Shaman", "Water Shield" },

    -- Warlock
    banish = { "Warlock", "Banish" },
    curseoftongues = { "Warlock", "Curse of Tongues" },
    deathcoil = { "Warlock", "Death Coil" },
    drainmana = { "Warlock", "Drain Mana" },
    fear = { "Warlock", "Fear" },
    fearfriend = { "Warlock", "Fear" },
    friendfeared = { "Warlock", "Fear" },
    fear2 = { "Warlock", "Howl of Terror" },
    metamorphosis = { "Warlock", "Metamorphosis" },
    seduction = { "Warlock", "Seduction" },
    shadowtrance = { "Warlock", "Shadow Trance" },
    spelllock = { "Warlock", "Spell Lock" },
    summonpet = { "Warlock", "Summon pet" },

    -- Warrior
    battlestance = { "Warrior", "Battle Stance" },
    berserkerrage = { "Warrior", "Berserker Rage" },
    berserkerstance = { "Warrior", "Berserker Stance" },
    bladestorm = { "Warrior", "Bladestorm" },
    bladestormdown = { "Warrior", "Bladestorm" },
    deathwish = { "Warrior", "Death Wish" },
    deathwishdown = { "Warrior", "Death Wish" },
    defensestance = { "Warrior", "Defensive Stance" },
    disarm = { "Warrior", "Disarm" },
    enragedregeneration = { "Warrior", "Enraged Regeneration" },
    fear3 = { "Warrior", "Intimidating Shout" },
    laststand = { "Warrior", "Last Stand" },
    pummel = { "Warrior", "Pummel" },
    rallyingcry = { "Warrior", "Rallying Cry" },
    recklessness = { "Warrior", "Recklessness" },
    recklessnessdown = { "Warrior", "Recklessness" },
    retaliation = { "Warrior", "Retaliation" },
    shieldbash = { "Warrior", "Shield Bash" },
    shieldwall = { "Warrior", "Shield Wall" },
    shieldwalldown = { "Warrior", "Shield Wall" },
    shockwave = { "Warrior", "Shockwave" },
    spellreflection = { "Warrior", "Spell Reflection" },
    sweepingstrikes = { "Warrior", "Sweeping Strikes" },

    -- Races
    berserking = { "Races", "Berserking" },
    bloodfury = { "Races", "Blood Fury" },
    cannibalize = { "Races", "Cannibalize" },
    eluneslight = { "Races", "Elune's Light" },
    shadowmeld = { "Races", "Shadowmeld" },
    skysight = { "Races", "Skysight" },
    stoneform = { "Races", "Stoneform" },
    trinket = { "Races", "Stun break (racial)" },
    willoftheforsaken = { "Races", "Will of the Forsaken" },

    -- Other
    bigheal = { "Other", "Big heals" },
    friendcountered = { "Other", "Interrupts on you" },
    resurrection = { "Other", "Resurrections" },
}
